export enum TokenType {
  GENERATED = 'GENERATED',
  PURCHASED = 'PURCHASED',
  TRANSFERRED_IN = 'TRANSFERRED_IN',
  TRANSFERRED_OUT = 'TRANSFERRED_OUT',
  SPENT = 'SPENT',
  REFUNDED = 'REFUNDED',
  EXPIRED = 'EXPIRED',
  AWARDED = 'AWARDED',
}
